[project]
name = "pwn-particle-filter"
version = "0.1.0"
description = ""
authors = [
    {name = "Vlad Korsakov",email = "ulqba@student.kit.edu"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy (>=2.3.5,<3.0.0)",
    "stonesoup (>=1.8,<2.0)",
    "ipykernel (>=7.1.0,<8.0.0)",
    "scipy (>=1.16.3,<2.0.0)",
    "deterministic-gaussian-sampling-fibonacci @ git+https://github.com/KIT-ISAS/deterministic_gaussian_sampling_fibonacci.git",
    "nbformat (>=5.10.4,<6.0.0)",
    "ipython (>=9.8.0,<10.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false
